import React, { useState, useCallback } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, LayoutChangeEvent } from 'react-native';
import Animated, {
  useSharedValue,
  useAnimatedStyle,
  withTiming,
  Easing,
} from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { Colors } from '@/constants/colors';
import { Typography, FontWeight } from '@/constants/typography';
import { Spacing, BorderRadius } from '@/constants/spacing';

const DISCLAIMER_TEXT = [
  'This tool provides general informational guidance about common household plumbing issues.',
  'It does not provide professional plumbing services, diagnoses, or repair instructions. The information generated by this assistant may be incomplete or inaccurate.',
  'Do not attempt repairs involving gas lines, boilers, pressurized plumbing systems, or major pipe work.',
  'Always consult a licensed plumber or qualified professional for inspection and repairs.',
  'By continuing, you acknowledge that you use this tool at your own risk.',
];

const TIMING_CONFIG = { duration: 300, easing: Easing.out(Easing.cubic) };

export function DisclaimerBanner() {
  const [expanded, setExpanded] = useState(false);
  const [contentHeight, setContentHeight] = useState(0);
  const animHeight = useSharedValue(0);
  const animRotate = useSharedValue(0);

  const onContentLayout = useCallback((e: LayoutChangeEvent) => {
    const h = e.nativeEvent.layout.height;
    if (h > 0 && contentHeight === 0) {
      setContentHeight(h);
    }
  }, [contentHeight]);

  const toggle = useCallback(() => {
    const next = !expanded;
    setExpanded(next);
    animHeight.value = withTiming(next ? 1 : 0, TIMING_CONFIG);
    animRotate.value = withTiming(next ? 1 : 0, TIMING_CONFIG);
  }, [expanded, animHeight, animRotate]);

  const bodyStyle = useAnimatedStyle(() => ({
    height: contentHeight > 0 ? animHeight.value * contentHeight : undefined,
    opacity: animHeight.value,
  }));

  const chevronStyle = useAnimatedStyle(() => ({
    transform: [{ rotate: `${animRotate.value * 180}deg` }],
  }));

  return (
    <View style={styles.container}>
      <TouchableOpacity
        style={styles.header}
        onPress={toggle}
        activeOpacity={0.7}
      >
        <Ionicons name="warning" size={18} color={Colors.warning} />
        <Text style={styles.title}>Home Maintenance Assistant Disclaimer</Text>
        <Animated.View style={chevronStyle}>
          <Ionicons name="chevron-down" size={18} color={Colors.grey500} />
        </Animated.View>
      </TouchableOpacity>

      <Animated.View style={[styles.bodyWrapper, bodyStyle]}>
        <View
          style={styles.body}
          onLayout={contentHeight === 0 ? onContentLayout : undefined}
        >
          {DISCLAIMER_TEXT.map((paragraph, i) => (
            <Text key={i} style={styles.paragraph}>
              {paragraph}
            </Text>
          ))}
        </View>
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    backgroundColor: Colors.warningBg,
    borderRadius: BorderRadius.card,
    marginHorizontal: Spacing.base,
    marginTop: Spacing.sm,
    overflow: 'hidden',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.md,
    gap: Spacing.sm,
  },
  title: {
    ...Typography.caption,
    fontWeight: FontWeight.semiBold,
    color: Colors.grey700,
    flex: 1,
  },
  bodyWrapper: {
    overflow: 'hidden',
  },
  body: {
    paddingHorizontal: Spacing.md,
    paddingBottom: Spacing.md,
  },
  paragraph: {
    ...Typography.caption,
    color: Colors.grey700,
    marginBottom: Spacing.sm,
  },
});
